# Generated by Django 5.1.5 on 2025-11-21 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0001_initial'),
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodo.periodo'),
        ),
    ]
