# Generated by Django 5.1.5 on 2025-12-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('movimiento', '0002_movimiento_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria'),
        ),
    ]
