# Generated by Django 5.1.5 on 2025-12-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('movimiento', '0003_movimiento_categoria'),
        ('periodo', '0006_remove_mapperiodocategoria_categoria_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.UniqueConstraint(fields=('concepto', 'fecha', 'monto'), name='unique_concepto_fecha_monto'),
        ),
    ]
