# Generated by Django 6.0 on 2025-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0004_movimiento_unique_concepto_fecha_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='concepto',
            field=models.CharField(max_length=255),
        ),
    ]
