# Generated by Django 5.1.5 on 2025-12-08 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria')),
            ],
        ),
    ]
