# Generated by Django 6.0 on 2025-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_gasto',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
