# Generated by Django 5.1.5 on 2025-12-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCategoriaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
    ]
