# Generated by Django 5.1.5 on 2025-12-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('objetivo', '0002_mapcategoriaobjetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcategoriaobjetivo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria'),
        ),
        migrations.AddField(
            model_name='mapcategoriaobjetivo',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objetivo.objetivo'),
        ),
    ]
