# Generated by Django 6.0 on 2025-12-14 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('objetivo', '0003_mapcategoriaobjetivo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcategoriaobjetivo',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='mapcategoriaobjetivo',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objetivo.objetivo'),
        ),
    ]
