# Generated by Django 6.0 on 2025-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objetivo', '0004_alter_mapcategoriaobjetivo_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='is_cumplido',
            field=models.BooleanField(default=False),
        ),
    ]
