# Generated by Django 5.1.5 on 2025-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('mes', models.DateField(max_length=255)),
                ('porc_ideal_fijo', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('porc_ideal_estimado', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('porc_ideal_obtenido', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
