# Generated by Django 5.1.5 on 2025-11-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='mes',
            new_name='fecha',
        ),
    ]
