# Generated by Django 5.1.5 on 2025-11-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0002_rename_mes_periodo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='porc_ideal_estimado',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='porc_ideal_fijo',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='porc_ideal_obtenido',
        ),
    ]
