# Generated by Django 5.1.5 on 2025-11-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0003_remove_periodo_porc_ideal_estimado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPeriodoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porc_ideal_fijo', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('porc_ideal_estimado', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('porc_ideal_obtenido', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
