# Generated by Django 5.1.5 on 2025-12-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('periodo', '0004_mapperiodocategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapperiodocategoria',
            name='categoria',
            field=models.ManyToManyField(to='categoria.categoria'),
        ),
        migrations.AddField(
            model_name='mapperiodocategoria',
            name='periodo',
            field=models.ManyToManyField(to='periodo.periodo'),
        ),
    ]
