# Generated by Django 5.1.5 on 2025-12-09 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('periodo', '0005_mapperiodocategoria_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapperiodocategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='mapperiodocategoria',
            name='periodo',
        ),
        migrations.AddField(
            model_name='mapperiodocategoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.categoria'),
        ),
        migrations.AddField(
            model_name='mapperiodocategoria',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodo.periodo'),
        ),
    ]
