# Generated by Django 6.0 on 2025-12-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('periodo', '0006_remove_mapperiodocategoria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapperiodocategoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='mapperiodocategoria',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='periodo.periodo'),
        ),
    ]
