# Generated by Django 6.0 on 2026-01-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0007_alter_mapperiodocategoria_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapperiodocategoria',
            name='ingreso_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='mapperiodocategoria',
            name='ingreso_fijo',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
