# Generated by Django 6.0 on 2026-06-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0009_remove_mapperiodocategoria_ingreso_estimado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapperiodocategoria',
            name='porc_ideal_obtenido',
        ),
    ]
